M48
; DRILL file KiCad 10.0.5 date 2026-09-06T20:40:05
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-06T20:40:05+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X90.0Y-130.0
X91.387Y-63.639
X209.0Y-130.0
X210.387Y-63.639
T2
X161.96Y-100.255
X161.96Y-116.375
M30
